name: getx_structure
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^5.4.3+1
  easy_localization: ^3.0.6
  flutter_gen: ^5.4.0
  flutter_secure_storage: ^9.0.0
  get_it: ^7.7.0
  go_router: ^14.0.2
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  talker_dio_logger: ^4.2.0
  talker_flutter: ^4.2.0
  fpdart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.2
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  pubspec_dependency_sorter: ^1.0.4

flutter_gen: 
  output: lib/core/assets/
  integrations: 
    flutter_svg: true
  assets: 
    outputs: 
      class_name: Assets
      package_parameter_enabled: false
    enabled: true
  fonts: 
    outputs: 
      class_name: AppFonts
    enabled: true
  line_length: 80


flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
